/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiChatConfirmRouteImport } from './routes/api/chat.confirm'
import { Route as ApiChatConfirmResponseRouteImport } from './routes/api/chat.confirm-response'
import { Route as ApiModelsActivateRouteImport } from './routes/api/models.activate'
import { Route as ApiRagIndexRouteImport } from './routes/api/rag.index'
import { Route as ApiRagDocumentsRouteImport } from './routes/api/rag.documents'
import { Route as ApiRagStatusRouteImport } from './routes/api/rag.status'
import { Route as ApiRagUploadRouteImport } from './routes/api/rag.upload'
import { Route as ApiSettingsResetRouteImport } from './routes/api/settings.reset'
import { Route as ApiSystemStatsRouteImport } from './routes/api/system.stats'
import { Route as ApiWorkspaceOpenFolderRouteImport } from './routes/api/workspace.open-folder'
import { Route as ApiWorkspaceRecentRouteImport } from './routes/api/workspace.recent'
import { Route as ApiWorkspaceResetRouteImport } from './routes/api/workspace.reset'
import { Route as ApiWorkspaceSetRouteImport } from './routes/api/workspace.set'
import { Route as ApiWorkspaceValidateRouteImport } from './routes/api/workspace.validate'
import { Route as ApiRagDocumentsDocIdRouteImport } from './routes/api/rag.documents.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatConfirmRoute = ApiChatConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatConfirmResponseRoute = ApiChatConfirmResponseRouteImport.update({
  id: '/confirm-response',
  path: '/confirm-response',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiModelsActivateRoute = ApiModelsActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => ApiModelsRoute,
} as any)
const ApiRagIndexRoute = ApiRagIndexRouteImport.update({
  id: '/api/rag/',
  path: '/api/rag/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagDocumentsRoute = ApiRagDocumentsRouteImport.update({
  id: '/api/rag/documents',
  path: '/api/rag/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagStatusRoute = ApiRagStatusRouteImport.update({
  id: '/api/rag/status',
  path: '/api/rag/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagUploadRoute = ApiRagUploadRouteImport.update({
  id: '/api/rag/upload',
  path: '/api/rag/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsResetRoute = ApiSettingsResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ApiSettingsRoute,
} as any)
const ApiSystemStatsRoute = ApiSystemStatsRouteImport.update({
  id: '/api/system/stats',
  path: '/api/system/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceOpenFolderRoute = ApiWorkspaceOpenFolderRouteImport.update({
  id: '/open-folder',
  path: '/open-folder',
  getParentRoute: () => ApiWorkspaceRoute,
} as any)
const ApiWorkspaceRecentRoute = ApiWorkspaceRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => ApiWorkspaceRoute,
} as any)
const ApiWorkspaceResetRoute = ApiWorkspaceResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ApiWorkspaceRoute,
} as any)
const ApiWorkspaceSetRoute = ApiWorkspaceSetRouteImport.update({
  id: '/set',
  path: '/set',
  getParentRoute: () => ApiWorkspaceRoute,
} as any)
const ApiWorkspaceValidateRoute = ApiWorkspaceValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => ApiWorkspaceRoute,
} as any)
const ApiRagDocumentsDocIdRoute = ApiRagDocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => ApiRagDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/api/chat/confirm': typeof ApiChatConfirmRoute
  '/api/chat/confirm-response': typeof ApiChatConfirmResponseRoute
  '/api/models/activate': typeof ApiModelsActivateRoute
  '/api/rag/documents': typeof ApiRagDocumentsRouteWithChildren
  '/api/rag/status': typeof ApiRagStatusRoute
  '/api/rag/upload': typeof ApiRagUploadRoute
  '/api/settings/reset': typeof ApiSettingsResetRoute
  '/api/system/stats': typeof ApiSystemStatsRoute
  '/api/workspace/open-folder': typeof ApiWorkspaceOpenFolderRoute
  '/api/workspace/recent': typeof ApiWorkspaceRecentRoute
  '/api/workspace/reset': typeof ApiWorkspaceResetRoute
  '/api/workspace/set': typeof ApiWorkspaceSetRoute
  '/api/workspace/validate': typeof ApiWorkspaceValidateRoute
  '/api/rag/': typeof ApiRagIndexRoute
  '/api/rag/documents/$docId': typeof ApiRagDocumentsDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/api/chat/confirm': typeof ApiChatConfirmRoute
  '/api/chat/confirm-response': typeof ApiChatConfirmResponseRoute
  '/api/models/activate': typeof ApiModelsActivateRoute
  '/api/rag/documents': typeof ApiRagDocumentsRouteWithChildren
  '/api/rag/status': typeof ApiRagStatusRoute
  '/api/rag/upload': typeof ApiRagUploadRoute
  '/api/settings/reset': typeof ApiSettingsResetRoute
  '/api/system/stats': typeof ApiSystemStatsRoute
  '/api/workspace/open-folder': typeof ApiWorkspaceOpenFolderRoute
  '/api/workspace/recent': typeof ApiWorkspaceRecentRoute
  '/api/workspace/reset': typeof ApiWorkspaceResetRoute
  '/api/workspace/set': typeof ApiWorkspaceSetRoute
  '/api/workspace/validate': typeof ApiWorkspaceValidateRoute
  '/api/rag': typeof ApiRagIndexRoute
  '/api/rag/documents/$docId': typeof ApiRagDocumentsDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/models': typeof ApiModelsRouteWithChildren
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/api/chat/confirm': typeof ApiChatConfirmRoute
  '/api/chat/confirm-response': typeof ApiChatConfirmResponseRoute
  '/api/models/activate': typeof ApiModelsActivateRoute
  '/api/rag/documents': typeof ApiRagDocumentsRouteWithChildren
  '/api/rag/status': typeof ApiRagStatusRoute
  '/api/rag/upload': typeof ApiRagUploadRoute
  '/api/settings/reset': typeof ApiSettingsResetRoute
  '/api/system/stats': typeof ApiSystemStatsRoute
  '/api/workspace/open-folder': typeof ApiWorkspaceOpenFolderRoute
  '/api/workspace/recent': typeof ApiWorkspaceRecentRoute
  '/api/workspace/reset': typeof ApiWorkspaceResetRoute
  '/api/workspace/set': typeof ApiWorkspaceSetRoute
  '/api/workspace/validate': typeof ApiWorkspaceValidateRoute
  '/api/rag/': typeof ApiRagIndexRoute
  '/api/rag/documents/$docId': typeof ApiRagDocumentsDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/models'
    | '/api/settings'
    | '/api/upload'
    | '/api/workspace'
    | '/api/chat/confirm'
    | '/api/chat/confirm-response'
    | '/api/models/activate'
    | '/api/rag/documents'
    | '/api/rag/status'
    | '/api/rag/upload'
    | '/api/settings/reset'
    | '/api/system/stats'
    | '/api/workspace/open-folder'
    | '/api/workspace/recent'
    | '/api/workspace/reset'
    | '/api/workspace/set'
    | '/api/workspace/validate'
    | '/api/rag/'
    | '/api/rag/documents/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/models'
    | '/api/settings'
    | '/api/upload'
    | '/api/workspace'
    | '/api/chat/confirm'
    | '/api/chat/confirm-response'
    | '/api/models/activate'
    | '/api/rag/documents'
    | '/api/rag/status'
    | '/api/rag/upload'
    | '/api/settings/reset'
    | '/api/system/stats'
    | '/api/workspace/open-folder'
    | '/api/workspace/recent'
    | '/api/workspace/reset'
    | '/api/workspace/set'
    | '/api/workspace/validate'
    | '/api/rag'
    | '/api/rag/documents/$docId'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/models'
    | '/api/settings'
    | '/api/upload'
    | '/api/workspace'
    | '/api/chat/confirm'
    | '/api/chat/confirm-response'
    | '/api/models/activate'
    | '/api/rag/documents'
    | '/api/rag/status'
    | '/api/rag/upload'
    | '/api/settings/reset'
    | '/api/system/stats'
    | '/api/workspace/open-folder'
    | '/api/workspace/recent'
    | '/api/workspace/reset'
    | '/api/workspace/set'
    | '/api/workspace/validate'
    | '/api/rag/'
    | '/api/rag/documents/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRouteWithChildren
  ApiRagDocumentsRoute: typeof ApiRagDocumentsRouteWithChildren
  ApiRagStatusRoute: typeof ApiRagStatusRoute
  ApiRagUploadRoute: typeof ApiRagUploadRoute
  ApiSystemStatsRoute: typeof ApiSystemStatsRoute
  ApiRagIndexRoute: typeof ApiRagIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/confirm': {
      id: '/api/chat/confirm'
      path: '/confirm'
      fullPath: '/api/chat/confirm'
      preLoaderRoute: typeof ApiChatConfirmRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/confirm-response': {
      id: '/api/chat/confirm-response'
      path: '/confirm-response'
      fullPath: '/api/chat/confirm-response'
      preLoaderRoute: typeof ApiChatConfirmResponseRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/models/activate': {
      id: '/api/models/activate'
      path: '/activate'
      fullPath: '/api/models/activate'
      preLoaderRoute: typeof ApiModelsActivateRouteImport
      parentRoute: typeof ApiModelsRoute
    }
    '/api/rag/': {
      id: '/api/rag/'
      path: '/api/rag'
      fullPath: '/api/rag/'
      preLoaderRoute: typeof ApiRagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/documents': {
      id: '/api/rag/documents'
      path: '/api/rag/documents'
      fullPath: '/api/rag/documents'
      preLoaderRoute: typeof ApiRagDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/status': {
      id: '/api/rag/status'
      path: '/api/rag/status'
      fullPath: '/api/rag/status'
      preLoaderRoute: typeof ApiRagStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/upload': {
      id: '/api/rag/upload'
      path: '/api/rag/upload'
      fullPath: '/api/rag/upload'
      preLoaderRoute: typeof ApiRagUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/reset': {
      id: '/api/settings/reset'
      path: '/reset'
      fullPath: '/api/settings/reset'
      preLoaderRoute: typeof ApiSettingsResetRouteImport
      parentRoute: typeof ApiSettingsRoute
    }
    '/api/system/stats': {
      id: '/api/system/stats'
      path: '/api/system/stats'
      fullPath: '/api/system/stats'
      preLoaderRoute: typeof ApiSystemStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/open-folder': {
      id: '/api/workspace/open-folder'
      path: '/open-folder'
      fullPath: '/api/workspace/open-folder'
      preLoaderRoute: typeof ApiWorkspaceOpenFolderRouteImport
      parentRoute: typeof ApiWorkspaceRoute
    }
    '/api/workspace/recent': {
      id: '/api/workspace/recent'
      path: '/recent'
      fullPath: '/api/workspace/recent'
      preLoaderRoute: typeof ApiWorkspaceRecentRouteImport
      parentRoute: typeof ApiWorkspaceRoute
    }
    '/api/workspace/reset': {
      id: '/api/workspace/reset'
      path: '/reset'
      fullPath: '/api/workspace/reset'
      preLoaderRoute: typeof ApiWorkspaceResetRouteImport
      parentRoute: typeof ApiWorkspaceRoute
    }
    '/api/workspace/set': {
      id: '/api/workspace/set'
      path: '/set'
      fullPath: '/api/workspace/set'
      preLoaderRoute: typeof ApiWorkspaceSetRouteImport
      parentRoute: typeof ApiWorkspaceRoute
    }
    '/api/workspace/validate': {
      id: '/api/workspace/validate'
      path: '/validate'
      fullPath: '/api/workspace/validate'
      preLoaderRoute: typeof ApiWorkspaceValidateRouteImport
      parentRoute: typeof ApiWorkspaceRoute
    }
    '/api/rag/documents/$docId': {
      id: '/api/rag/documents/$docId'
      path: '/$docId'
      fullPath: '/api/rag/documents/$docId'
      preLoaderRoute: typeof ApiRagDocumentsDocIdRouteImport
      parentRoute: typeof ApiRagDocumentsRoute
    }
  }
}

interface ApiChatRouteChildren {
  ApiChatConfirmRoute: typeof ApiChatConfirmRoute
  ApiChatConfirmResponseRoute: typeof ApiChatConfirmResponseRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatConfirmRoute: ApiChatConfirmRoute,
  ApiChatConfirmResponseRoute: ApiChatConfirmResponseRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

interface ApiModelsRouteChildren {
  ApiModelsActivateRoute: typeof ApiModelsActivateRoute
}

const ApiModelsRouteChildren: ApiModelsRouteChildren = {
  ApiModelsActivateRoute: ApiModelsActivateRoute,
}

const ApiModelsRouteWithChildren = ApiModelsRoute._addFileChildren(
  ApiModelsRouteChildren,
)

interface ApiSettingsRouteChildren {
  ApiSettingsResetRoute: typeof ApiSettingsResetRoute
}

const ApiSettingsRouteChildren: ApiSettingsRouteChildren = {
  ApiSettingsResetRoute: ApiSettingsResetRoute,
}

const ApiSettingsRouteWithChildren = ApiSettingsRoute._addFileChildren(
  ApiSettingsRouteChildren,
)

interface ApiWorkspaceRouteChildren {
  ApiWorkspaceOpenFolderRoute: typeof ApiWorkspaceOpenFolderRoute
  ApiWorkspaceRecentRoute: typeof ApiWorkspaceRecentRoute
  ApiWorkspaceResetRoute: typeof ApiWorkspaceResetRoute
  ApiWorkspaceSetRoute: typeof ApiWorkspaceSetRoute
  ApiWorkspaceValidateRoute: typeof ApiWorkspaceValidateRoute
}

const ApiWorkspaceRouteChildren: ApiWorkspaceRouteChildren = {
  ApiWorkspaceOpenFolderRoute: ApiWorkspaceOpenFolderRoute,
  ApiWorkspaceRecentRoute: ApiWorkspaceRecentRoute,
  ApiWorkspaceResetRoute: ApiWorkspaceResetRoute,
  ApiWorkspaceSetRoute: ApiWorkspaceSetRoute,
  ApiWorkspaceValidateRoute: ApiWorkspaceValidateRoute,
}

const ApiWorkspaceRouteWithChildren = ApiWorkspaceRoute._addFileChildren(
  ApiWorkspaceRouteChildren,
)

interface ApiRagDocumentsRouteChildren {
  ApiRagDocumentsDocIdRoute: typeof ApiRagDocumentsDocIdRoute
}

const ApiRagDocumentsRouteChildren: ApiRagDocumentsRouteChildren = {
  ApiRagDocumentsDocIdRoute: ApiRagDocumentsDocIdRoute,
}

const ApiRagDocumentsRouteWithChildren = ApiRagDocumentsRoute._addFileChildren(
  ApiRagDocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiModelsRoute: ApiModelsRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ApiWorkspaceRoute: ApiWorkspaceRouteWithChildren,
  ApiRagDocumentsRoute: ApiRagDocumentsRouteWithChildren,
  ApiRagStatusRoute: ApiRagStatusRoute,
  ApiRagUploadRoute: ApiRagUploadRoute,
  ApiSystemStatsRoute: ApiSystemStatsRoute,
  ApiRagIndexRoute: ApiRagIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
